### PR TITLE
always depend on fixed versions, otherwise you are automagically conf…

### PR DESCRIPTION
**Pull request by eduarddrenth**
…ronted with updates

### CODE REVIEW

**Comment by dmj** [comment]
What I want to achieve is, that the Java package has a runtime dependency on the SchXslt stylesheets but not on a particular version of it. Do you know a way to express this in Maven?

**Comment by eduarddrenth** [comment]
Well [1.4.7,) does exactly that. Buildtime that's ok, your tests run against the version that's pulled in. But users of your lib may pull in a higher (possibly untested) version. So I would fix the version, users can always choose to use a higher version of schxslt. I can see the advantage of having to publish less often, but that doesn't outweigh the disadvantage of pulling in possibly untested schxslt lib I think

**Comment by eduarddrenth** [comment]
So, you released 1.5, I depend on 2.0.2 java, which pulls that in because of [1.4.7,) and I get:

```
Could not resolve dependencies for project org.fryske-akademy:teidictionaries:jar:1.3-SNAPSHOT: Failed to collect dependencies at name.dmaus.schxslt:java:jar:2.0.2 -> name.dmaus.schxslt:schxslt:jar:1.5
```
solvable of-course, but this illustrates why I suggest fixed versions

**Comment by dmj** [comment]
Convinced!

**Pull request merged**
